
# Authentication(Login)
POST http://localhost:8079/api/auth/local
Content-Type: application/json

    {
        "identifier":"s6502041610136@email.kmutnb.ac.th",
        "password" : "p@ssw@rd"
    }